#!/bin/bash
#
# My prefered way of handling Pop!_OS

gsettings set org.gnome.shell.keybindings switch-to-application-1 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-2 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-3 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-4 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-5 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-6 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-7 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-8 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-9 "[]"

gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>Home', '<Super>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Super>7']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Super>8']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Super>9']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Super>9']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['<Primary><Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Primary><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings close "['<Super>q']"

gsettings set org.gnome.desktop.wm.keybindings maximize "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "[]"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "[]"

gsettings set org.gnome.shell.keybindings shift-overview-up "['<Primary><Super>Up']"
gsettings set org.gnome.shell.keybindings shift-overview-down "['<Primary><Super>Down']"

gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Alt><Super>Up']"
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Alt><Super>Left']"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Alt><Super>Right']"

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Shift><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left "['<Shift><Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings unmaximize "[]"

gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true

# Menu on left
gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize:appmenu'

# Pop shell stuff
gsettings set org.gnome.shell.extensions.pop-shell focus-up "['<Super>Up']"
gsettings set org.gnome.shell.extensions.pop-shell focus-down "['<Super>Down']"
gsettings set org.gnome.shell.extensions.pop-shell focus-left "['<Super>Left']"
gsettings set org.gnome.shell.extensions.pop-shell focus-right "['<Super>Right']"
gsettings set org.gnome.shell.extensions.pop-shell activate-launcher "['<Super>space']"
