#!/bin/sh
#
# Flip win and alt on pc-keyboard using xkb-options on linux
#
# ALT_L = 64
# SUPER/WIN_L = 133 <- Guessing
#
# ALT_R = 108
# SUPER/WIN_R = 134
#
# Use gnome-tweak/dconf-editor tool
# * flip alt-win
# * att third-level choice to right-win
#
# Make sure ctrl-space is not bind to flipping layouts (iBus crap)...
#
dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:escape','lv3:rwin','altwin:swap_alt_win','lv3:rwin_switch']"
