#!/bin/sh
#
# First scales up all UI elements 2 times and then downscales
# everything 1.5 times.
#
# gsettings only works with integers and doesn't blur, xrandr blurs
# and works with fractions...

gsettings set org.gnome.desktop.interface scaling-factor 2
xrandr --output DP-1 --scale 1.5x1.5 --panning 5760x3240