# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[\$>](green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[time]
disabled = false

[git_status]
# The processing felt to slow for me :/
disabled = true
