#!/bin/bash
function up_arch {
    pacaur -Syu 2> /dev/null
}

function up_elementary {
    sudo apt update && sudo apt dist-upgrade 2> /dev/null
}

case $(uname -s) in
    Darwin|FreeBSD)
        brew update && brew upgrade
        ;;
    Linux)
        up_arch || up_elementary
        ;;
esac

