#!/bin/bash
function up_arch {
    yay -Syu 2> /dev/null
}

function up_pop {
    sudo apt update && sudo apt full-upgrade 2> /dev/null
}

function up_fedora {
    sudo dnf update && sudo dnf upgrade
}

case $(uname -s) in
    Darwin|FreeBSD)
        brew update && brew upgrade -n
        ;;
    Linux)
        case $(lsb_release -is) in
            Fedora)
                up_fedora
                ;;
            Pop)
                up_pop
                ;;
            Elementary)
                up_pop
                ;;
            Arch)
                up_arch
                ;;
        esac
esac

